### PR TITLE
Simplify installation and documentation

### PR DESCRIPTION
**Pull request by rrthomas**
Remove some distractions, fix some nits.

Remove unused check target.

Remove byte-compilation.

### CODE REVIEW

**Comment by jart** [comment]
You have a talent for making things simple! Out of curiosity, why `C-c i` instead of `C-c C-h`? The 'i' mnemonic is definitely a better choice, and I'm assuming not having it be C-i makes it less likely to conflict with things?

**Comment by rrthomas** [comment]
`C-c C-h` seems already to be used in other applications, and given that you're already interfering with the user's private keymap, I thought it wise to suggest a default unlikely to be used, and also more mnemonic. `C-c C-i` I discovered, when I tried it, is an existing prefix keymap!

**Comment by jart** [comment]
I would take 'index' out of the default rule because that requires some special files to be downloaded and I don't want people to break the world accidentally when they expected just the lisp to compile.

**Comment by rrthomas** [comment]
Aye-aye cap'n.

**Comment by jart** [comment]
:+1:

**Pull request merged**
